### ISSUE TITLE
Ionic5 flash does not work

### ISSUE THREAD

**Issue by shigua** [capacitor-community/camera-preview#102] opened 2021-02-26 08:22 UTC
CameraPreview.setFlashMode({ flashMode: "on" });  does not work

**Comment by AhmedBenRouha01** [comment] 2021-04-15 08:48
what error do you get ?
did you try "torch" instead of "on" ?

**Comment by pbowyer** [comment] 2021-12-16 21:32
Closing as cannot reproduce. Perhaps you used a flash mode which the phone did not support?

**Closed by pbowyer** 2021-12-16 21:32 UTC
